use Sandpit
Go

CREATE table dbo.Patient_Record (
	[Row Number] [int] NOT NULL,
	[Effective Date/Time] [datetime] NULL,
	[Healthcare Organisation] [varchar](50) NULL,
	[Hospital Number] [varchar](50) Not NULL,
	[National Number] [varchar](50) NULL,
	[National Number Status] [int] NULL,
	[Title] [varchar](25) NULL,
	[Surname] [varchar](50) NULL,
	[Forename] [varchar](50) NULL,
	[Middle Name(s)] [varchar](50) NULL,
	[Preferred Name] [varchar](50) NULL,
	[Date/Time of Birth] [datetime] NULL,
	[Date/Time of Death] [datetime] NULL,
	[Sex at Birth Code] [varchar](50) NULL,
	[Gender Identity Code] [varchar](50) NULL,
	[Administrative Gender Code] [varchar](50) NULL,
	[Marital Status Code] [varchar](50) NULL,
	[Religion Code] [varchar](50) NULL,
	[Ethnic Category Code] [varchar](50) NULL,
	[Nationality Code] [varchar](50) NULL,
	[Primary Language Code] [varchar](50) NULL,
	[Translation Required] [varchar](50) NULL,
	[Preferred Letter Format] [varchar](2) NULL,
	[Communication Preference Code] [varchar](3) NULL,
	[Preferred Contact Time] [varchar](250) NULL,
	[SMS Consent] [bit] NULL,
	[Address Street] [varchar](500) NULL,
	[Address Area] [varchar](500) NULL,
	[Address City] [varchar](500) NULL,
	[Address County] [varchar](500) NULL,
	[Address PostCode] [varchar](500) NULL,
	[Address Country] [varchar](500) NULL,
	[Temporary Address Street] [varchar](500) NULL,
	[Temporary Address Area] [varchar](500) NULL,
	[Temporary Address City] [varchar](500) NULL,
	[Temporary Address County] [varchar](500) NULL,
	[Temporary Address PostCode] [varchar](500) NULL,
	[Temporary Address Country] [varchar](500) NULL,
	[Temporary Address Expires] [date] NULL,
	[Registered GP Code] [varchar](100) NULL,
	[Registered GP Title] [varchar](50) NULL,
	[Registered GP Surname] [varchar](50) NULL,
	[Registered GP Forename] [varchar](50) NULL,
	[Registered GP Middle Name(s)] [varchar](50) NULL,
	[Registered GP Practice Code] [varchar](50) NULL,
	[Registered GP Practice Name] [varchar](100) NULL,
	[Nominted Pharmacy Code] [varchar](50) NULL,
	[Optician Code] [varchar](50) NULL,
	[Dental Practice Code] [varchar](50) NULL,
	[Pregnant Indicator] [bit] NULL,
	[Last Menstrual Period Date] [date] NULL,
	[Estimated Due Date] [date] NULL,
	[Birth City] [varchar](85) NULL,
	[Birth District] [varchar](85) NULL,
	[Birth Country] [varchar](3) NULL,
	[Birth Order] [varchar](3) NULL,
	[Occupation] [varchar](100) NULL,
	[School Code] [varchar](50) NULL,
	[Unknown Patient] [bit] NULL,
	[Next of Kin Address Divulgable to Patient] [bit] NULL,
	[Restricted] [bit] NULL,
	[Ex-Armed Forces Indicator Code] [varchar](2) NULL,
	[Witheld Identity Reason Code] [varchar](2) NULL,
	[Estimated Age] [bit] NULL,
	[EPS Exemption Reason] [varchar](16) NULL,
	[Correspondence Addressee] [varchar](100) NULL,
	[Correspondence Address Street] [varchar](100) NULL,
	[Correspondence Address Area] [varchar](100) NULL,
	[Correspondence Address City] [varchar](100) NULL,
	[Correspondence Address County] [varchar](100) NULL,
	[Correspondence Address PostCode] [varchar](10) NULL,
	[Correspondence Address Country] [varchar](100) NULL,
	[Correspondence Address Expires] [date] NULL,
	[Communication Restriction Reason] [varchar](10) NULL,
	[Communication Restriction Expires] [date] NULL,
	[Preferred Letter Delivery] [varchar](2) NULL,
	[Preferred Notification Delivery] [varchar](2) NULL,
	[Overseas Visitor Charging Category] [varchar](2) NULL,
	[Overseas Visitor Charging Start Date] [date] NULL,
	[Secondary Hospital Number] [varchar](32) NULL,
	[Alternate hospital number] [varchar](32) NULL,
	[Registered GP From Date] [date] NULL,
	[Address From Date] [date] NULL,
	[Temporary Address From Date] [date] NULL,
	[Correspondence Address From Date] [date] NULL,
	[Death Time Type] [varchar](20) NULL,
	[Overseas Visitor Charging End Date] [date] NULL,
 CONSTRAINT [PK_Patient_Record] PRIMARY KEY CLUSTERED ([Hospital Number])
 );

 GO 


 Use Sandpit
 Go
 Drop Table dbo.Patient_Record