USE [Sandpit]
GO

/****** Object:  Table [dbo].[Patient Record]    Script Date: 22/03/2026 14:18:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Patient Record](
	[Row Number] [varchar](50) NULL,
	[Effective Date Time] [varchar](50) NULL,
	[Healthcare Organisation] [varchar](50) NULL,
	[Hospital Number] [varchar](50) NULL,
	[National Number] [varchar](50) NULL,
	[National Number Status] [varchar](50) NULL,
	[Title] [varchar](50) NULL,
	[Surname] [varchar](50) NULL,
	[Forename] [varchar](50) NULL,
	[Middle Name(s)] [varchar](50) NULL,
	[Preferred Name] [varchar](50) NULL,
	[Date Time of Birth] [varchar](50) NULL,
	[Date Time of Death] [varchar](50) NULL,
	[Sex at Birth Code] [varchar](50) NULL,
	[Gender Identity Code] [varchar](50) NULL,
	[Administrative Gender Code] [varchar](50) NULL,
	[Marital Status Code] [varchar](50) NULL,
	[Religion Code] [varchar](50) NULL,
	[Ethnic Category Code] [varchar](50) NULL,
	[Nationality Code] [varchar](50) NULL,
	[Primary Language Code] [varchar](50) NULL,
	[Translation Required] [varchar](50) NULL,
	[Preferred Letter Format] [varchar](50) NULL,
	[Communication Preference Code] [varchar](50) NULL,
	[Preferred Contact Time] [varchar](50) NULL,
	[SMS Consent] [varchar](50) NULL,
	[Address Street] [varchar](50) NULL,
	[Address Area] [varchar](50) NULL,
	[Address City] [varchar](50) NULL,
	[Address County] [varchar](50) NULL,
	[Address PostCode] [varchar](50) NULL,
	[Address Country] [varchar](50) NULL,
	[Temporary Address Street] [varchar](50) NULL,
	[Temporary Address Area] [varchar](50) NULL,
	[Temporary Address City] [varchar](50) NULL,
	[Temporary Address County] [varchar](50) NULL,
	[Temporary Address PostCode] [varchar](50) NULL,
	[Temporary Address Country] [varchar](50) NULL,
	[Temporary Address Expires] [varchar](50) NULL,
	[Registered GP Code] [varchar](50) NULL,
	[Registered GP Title] [varchar](50) NULL,
	[Registered GP Surname] [varchar](50) NULL,
	[Registered GP Forename] [varchar](50) NULL,
	[Registered GP Middle Name(s)] [varchar](50) NULL,
	[Registered GP Practice Code] [varchar](50) NULL,
	[Registered GP Practice Name] [varchar](50) NULL,
	[Nominted Pharmacy Code] [varchar](50) NULL,
	[Optician Code] [varchar](50) NULL,
	[Dental Practice Code] [varchar](50) NULL,
	[Pregnant Indicator] [varchar](50) NULL,
	[Last Menstrual Period Date] [varchar](50) NULL,
	[Estimated Due Date] [varchar](50) NULL,
	[Birth City] [varchar](50) NULL,
	[Birth District] [varchar](50) NULL,
	[Birth Country] [varchar](50) NULL,
	[Birth Order] [varchar](50) NULL,
	[Occupation] [varchar](50) NULL,
	[School Code] [varchar](50) NULL,
	[Unknown Patient] [varchar](50) NULL,
	[Next of Kin Address Divulgable to Patient] [varchar](50) NULL,
	[Restricted] [varchar](50) NULL,
	[Ex-Armed Forces Indicator Code] [varchar](50) NULL,
	[Witheld Identity Reason Code] [varchar](50) NULL,
	[Estimated Age] [varchar](50) NULL,
	[EPS Exemption Reason] [varchar](50) NULL,
	[Correspondence Addressee] [varchar](50) NULL,
	[Correspondence Address Street] [varchar](50) NULL,
	[Correspondence Address Area] [varchar](50) NULL,
	[Correspondence Address City] [varchar](50) NULL,
	[Correspondence Address County] [varchar](50) NULL,
	[Correspondence Address PostCode] [varchar](50) NULL,
	[Correspondence Address Country] [varchar](50) NULL,
	[Correspondence Address Expires] [varchar](50) NULL,
	[Communication Restriction Reason] [varchar](50) NULL,
	[Communication Restriction Expires] [varchar](50) NULL,
	[Preferred Letter Delivery] [varchar](50) NULL,
	[Preferred Notification Delivery] [varchar](50) NULL,
	[Overseas Visitor Charging Category] [varchar](50) NULL,
	[Overseas Visitor Charging Start Date] [varchar](50) NULL,
	[Secondary Hospital Number] [varchar](50) NULL,
	[Alternate hospital number] [varchar](50) NULL,
	[Registered GP From Date] [varchar](50) NULL,
	[Address From Date] [varchar](50) NULL,
	[Temporary Address From Date] [varchar](50) NULL,
	[Correspondence Address From Date] [varchar](50) NULL,
	[Death Time Type] [varchar](50) NULL,
	[Overseas Visitor Charging End Date] [varchar](50) NULL,
	[InsertedOn] [varchar](50) NULL,
	[SysStartTime] [varchar](50) NULL,
	[SysEndTime] [varchar](50) NULL
) ON [PRIMARY]
GO


