USE Sandpit;
GO
IF OBJECT_ID('dbo.Patient_Record', 'U') IS NOT NULL
DROP TABLE dbo.Patient_Record

SELECT
    TRY_CONVERT(INT, NULLIF([ROW_NUMBER], 'NULL'))                            AS [Row Number],
    TRY_CONVERT(datetime, NULLIF([Effective_Date_Time], 'NULL'))              AS [Effective Date/Time],
    NULLIF([Healthcare_Organisation], 'NULL')                                 AS [Healthcare Organisation],
    NULLIF([Hospital_Number], 'NULL')                                          AS [Hospital Number],
    NULLIF([National_Number], 'NULL')                                          AS [National Number],
    TRY_CONVERT(int, NULLIF([National_Number_Status], 'NULL'))                 AS [National Number Status],
    NULLIF([Title], 'NULL')                                                    AS [Title],
    NULLIF([Surname], 'NULL')                                                  AS [Surname],
    NULLIF([Forename], 'NULL')                                                 AS [Forename],
    NULLIF([Middle_Name_s], 'NULL')                                            AS [Middle Name(s)],
    NULLIF([Preferred_Name], 'NULL')                                           AS [Preferred Name],
    TRY_CONVERT(datetime, NULLIF([Date_Time_of_Birth], 'NULL'))               AS [Date/Time of Birth],
    TRY_CONVERT(datetime, NULLIF([Date_Time_of_Death], 'NULL'))               AS [Date/Time of Death],
    NULLIF([Sex_at_Birth_Code], 'NULL')                                        AS [Sex at Birth Code],
    NULLIF([Gender_Identity_Code], 'NULL')                                     AS [Gender Identity Code],
    NULLIF([Administrative_Gender_Code], 'NULL')                               AS [Administrative Gender Code],
    NULLIF([Marital_Status_Code], 'NULL')                                      AS [Marital Status Code],
    NULLIF([Religion_Code], 'NULL')                                            AS [Religion Code],
    NULLIF([Ethnic_Category_Code], 'NULL')                                     AS [Ethnic Category Code],
    NULLIF([Nationality_Code], 'NULL')                                         AS [Nationality Code],
    NULLIF([Primary_Language_Code], 'NULL')                                    AS [Primary Language Code],
    NULLIF([Translation_Required], 'NULL')                                     AS [Translation Required],
    NULLIF([Preferred_Letter_Format], 'NULL')                                  AS [Preferred Letter Format],
    NULLIF([Communication_Preference_Code], 'NULL')                            AS [Communication Preference Code],
    NULLIF([Preferred_Contact_Time], 'NULL')                                   AS [Preferred Contact Time],
    TRY_CONVERT(bit, NULLIF([SMS_Consent], 'NULL'))                            AS [SMS Consent],
    NULLIF([Address_Street], 'NULL')                                           AS [Address Street],
    NULLIF([Address_Area], 'NULL')                                             AS [Address Area],
    NULLIF([Address_City], 'NULL')                                             AS [Address City],
    NULLIF([Address_County], 'NULL')                                           AS [Address County],
    NULLIF([Address_PostCode], 'NULL')                                         AS [Address PostCode],
    NULLIF([Address_Country], 'NULL')                                          AS [Address Country],
    NULLIF([Temporary_Address_Street], 'NULL')                                 AS [Temporary Address Street],
    NULLIF([Temporary_Address_Area], 'NULL')                                   AS [Temporary Address Area],
    NULLIF([Temporary_Address_City], 'NULL')                                   AS [Temporary Address City],
    NULLIF([Temporary_Address_County], 'NULL')                                 AS [Temporary Address County],
    NULLIF([Temporary_Address_PostCode], 'NULL')                               AS [Temporary Address PostCode],
    NULLIF([Temporary_Address_Country], 'NULL')                                AS [Temporary Address Country],
    TRY_CONVERT(date, NULLIF([Temporary_Address_Expires], 'NULL'))             AS [Temporary Address Expires],
    NULLIF([Registered_GP_Code], 'NULL')                                       AS [Registered GP Code],
    NULLIF([Registered_GP_Title], 'NULL')                                      AS [Registered GP Title],
    NULLIF([Registered_GP_Surname], 'NULL')                                    AS [Registered GP Surname],
    NULLIF([Registered_GP_Forename], 'NULL')                                   AS [Registered GP Forename],
    NULLIF([Registered_GP_Middle_Name_s], 'NULL')                              AS [Registered GP Middle Name(s)],
    NULLIF([Registered_GP_Practice_Code], 'NULL')                              AS [Registered GP Practice Code],
    NULLIF([Registered_GP_Practice_Name], 'NULL')                              AS [Registered GP Practice Name],
    NULLIF([Nominted_Pharmacy_Code], 'NULL')                                   AS [Nominted Pharmacy Code],
    NULLIF([Optician_Code], 'NULL')                                            AS [Optician Code],
    NULLIF([Dental_Practice_Code], 'NULL')                                     AS [Dental Practice Code],
    TRY_CONVERT(bit, NULLIF([Pregnant_Indicator], 'NULL'))                     AS [Pregnant Indicator],
    TRY_CONVERT(date, NULLIF([Last_Menstrual_Period_Date], 'NULL'))            AS [Last Menstrual Period Date],
    TRY_CONVERT(date, NULLIF([Estimated_Due_Date], 'NULL'))                    AS [Estimated Due Date],
    NULLIF([Birth_City], 'NULL')                                               AS [Birth City],
    NULLIF([Birth_District], 'NULL')                                           AS [Birth District],
    NULLIF([Birth_Country], 'NULL')                                            AS [Birth Country],
    NULLIF([Birth_Order], 'NULL')                                              AS [Birth Order],
    NULLIF([Occupation], 'NULL')                                               AS [Occupation],
    NULLIF([School_Code], 'NULL')                                              AS [School Code],
    TRY_CONVERT(bit, NULLIF([Unknown_Patient], 'NULL'))                        AS [Unknown Patient],
    TRY_CONVERT(bit, NULLIF([Next_of_Kin_Address_Divulgable_to_Patient], 'NULL')) AS [Next of Kin Address Divulgable to Patient],
    TRY_CONVERT(bit, NULLIF([Restricted], 'NULL'))                             AS [Restricted],
    NULLIF([Ex_Armed_Forces_Indicator_Code], 'NULL')                           AS [Ex-Armed Forces Indicator Code],
    NULLIF([Witheld_Identity_Reason_Code], 'NULL')                             AS [Witheld Identity Reason Code],
    TRY_CONVERT(bit, NULLIF([Estimated_Age], 'NULL'))                          AS [Estimated Age],
    NULLIF([EPS_Exemption_Reason], 'NULL')                                     AS [EPS Exemption Reason],
    NULLIF([Correspondence_Addressee], 'NULL')                                 AS [Correspondence Addressee],
    NULLIF([Correspondence_Address_Street], 'NULL')                            AS [Correspondence Address Street],
    NULLIF([Correspondence_Address_Area], 'NULL')                              AS [Correspondence Address Area],
    NULLIF([Correspondence_Address_City], 'NULL')                              AS [Correspondence Address City],
    NULLIF([Correspondence_Address_County], 'NULL')                            AS [Correspondence Address County],
    NULLIF([Correspondence_Address_PostCode], 'NULL')                          AS [Correspondence Address PostCode],
    NULLIF([Correspondence_Address_Country], 'NULL')                           AS [Correspondence Address Country],
    TRY_CONVERT(date, NULLIF([Correspondence_Address_Expires], 'NULL'))        AS [Correspondence Address Expires],
    NULLIF([Communication_Restriction_Reason], 'NULL')                         AS [Communication Restriction Reason],
    TRY_CONVERT(date, NULLIF([Communication_Restriction_Expires], 'NULL'))     AS [Communication Restriction Expires],
    NULLIF([Preferred_Letter_Delivery], 'NULL')                                AS [Preferred Letter Delivery],
    NULLIF([Preferred_Notification_Delivery], 'NULL')                          AS [Preferred Notification Delivery],
    NULLIF([Overseas_Visitor_Charging_Category], 'NULL')                       AS [Overseas Visitor Charging Category],
    TRY_CONVERT(date, NULLIF([Overseas_Visitor_Charging_Start_Date], 'NULL'))  AS [Overseas Visitor Charging Start Date],
    NULLIF([Secondary_Hospital_Number], 'NULL')                                AS [Secondary Hospital Number],
    NULLIF([Alternate_hospital_number], 'NULL')                                AS [Alternate hospital number],
    TRY_CONVERT(date, NULLIF([Registered_GP_From_Date], 'NULL'))               AS [Registered GP From Date],
    TRY_CONVERT(date, NULLIF([Address_From_Date], 'NULL'))                     AS [Address From Date],
    TRY_CONVERT(date, NULLIF([Temporary_Address_From_Date], 'NULL'))           AS [Temporary Address From Date],
    TRY_CONVERT(date, NULLIF([Correspondence_Address_From_Date], 'NULL'))      AS [Correspondence Address From Date],
    NULLIF([Death_Time_Type], 'NULL')                                          AS [Death Time Type],
    TRY_CONVERT(date, NULLIF([Overseas_Visitor_Charging_End_Date], 'NULL'))    AS [Overseas Visitor Charging End Date],
    NULLIF([InsertedOn], 'NULL')                                               AS [InsertedOn],
    NULLIF([SysStartTime], 'NULL')                                             AS [SysStartTime],
    NULLIF([SysEndTime], 'NULL')                                               AS [SysEndTime]
INTO dbo.Patient_Record
FROM dbo.PMI_Patient_Raw;
GO